//! Right-pane tab implementations.
//!
//! Each tab is a small self-contained module so the per-tab state
//! and render code stays close together. The [`RightTab`] enum is
//! the single shared identifier; `tabs_for_mode` resolves the set
//! of tabs reachable for a given model mode hint.

pub mod chat;
pub mod embed;
pub mod input_pane;
pub mod logs;
pub mod rerank;
pub mod settings;

use crate::gguf::metadata::ModeHint;

/// Identifier for one right-pane tab. `Logs` is always reachable;
/// the mode-specific tabs become reachable when the focused model
/// is `Ready` and its `ModeHint` matches.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RightTab {
  Logs,
  Chat,
  Embed,
  Rerank,
  /// Launch-parameter form. Editable for not-yet-launched models;
  /// read-only for running models (shows the params used).
  Settings,
}

impl RightTab {
  pub fn label(&self) -> &'static str {
    match self {
      RightTab::Logs => "Logs",
      RightTab::Chat => "Chat",
      RightTab::Embed => "Embed",
      RightTab::Rerank => "Rerank",
      RightTab::Settings => "Settings",
    }
  }
}

/// One-off events generated by async tab tasks (embed, rerank).
/// Lives here rather than in `tui::events` so per-tab modules
/// (`tabs::embed`, `tabs::rerank`) don't need to reach up into the
/// event-loop module. The chat tab streams via its own
/// `ChatStreamMsg` channel held inside `ChatTabState`; embed/rerank
/// only need a single result message so the receivers live on their
/// respective tab states.
#[derive(Debug)]
pub enum TabEvent {
  EmbedOk(crate::tui::oai_client::EmbedResult),
  EmbedErr(String),
  RerankOk(Vec<(usize, f64)>),
  RerankErr(String),
}

/// Tabs available for a model with the supplied mode hint. The
/// renderer only exposes the second tab when the model is `Ready`;
/// this helper just declares which tab type is appropriate.
pub fn tabs_for_mode(mode: ModeHint) -> Vec<RightTab> {
  // Settings is always present so the user can review/edit launch
  // params for the focused model. The mode-specific surface (Chat /
  // Embed / Rerank) sits between Logs and Settings.
  match mode {
    ModeHint::Chat => vec![RightTab::Logs, RightTab::Chat, RightTab::Settings],
    ModeHint::Embedding => vec![RightTab::Logs, RightTab::Embed, RightTab::Settings],
    ModeHint::Rerank => vec![RightTab::Logs, RightTab::Rerank, RightTab::Settings],
    ModeHint::Unknown => vec![RightTab::Logs, RightTab::Settings],
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn unknown_mode_exposes_logs_and_settings() {
    assert_eq!(
      tabs_for_mode(ModeHint::Unknown),
      vec![RightTab::Logs, RightTab::Settings]
    );
  }

  #[test]
  fn chat_mode_pairs_logs_chat_settings() {
    assert_eq!(
      tabs_for_mode(ModeHint::Chat),
      vec![RightTab::Logs, RightTab::Chat, RightTab::Settings]
    );
  }

  #[test]
  fn embedding_mode_pairs_logs_embed_settings() {
    assert_eq!(
      tabs_for_mode(ModeHint::Embedding),
      vec![RightTab::Logs, RightTab::Embed, RightTab::Settings]
    );
  }
}
